- name: Install madek dependencies
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - memcached
    - libimage-exiftool-perl
    - imagemagick


- name: Create target dir 
  file: path={{madek_root_dir}}
        owner=madek
        group=madek
        state=directory
        mode=0755

- debug: var=madek_git_ref
  tags: [debug]

- name: Git clone or update project
  sudo: True
  sudo_user: madek
  git:  repo=https://github.com/zhdk/madek.git
        dest={{madek_root_dir}}
        version={{madek_git_ref}}
        update=yes
        force=yes
  register: git_clone_or_update
  tags: [debug]
  #failed_when: "'Local modifications exist' in git_clone_or_update.msg"
  #changed_when: git_clone_or_update.before != git_clone_or_update.after

- name: Create target dir 
  file: path=/etc/madek
        owner=root
        group=root
        state=directory
        recurse=true
        mode=0600

- shell:  head -c 64 /dev/urandom | base64 --wrap=0 > /etc/madek/random.txt
          creates=/etc/madek/random.txt

- shell : "cat /etc/madek/random.txt"
  register: random_base
  changed_when: False

- name: Configure secrets
  template: src=secrets.yml
            dest={{madek_root_dir}}/config/secrets.yml
            owner=madek
            group=madek
            mode=0600

  template: src=settings.local.yml
            dest={{madek_root_dir}}/config/settings.local.yml
            owner=madek
            group=madek
            mode=0640

- name: Configure database
  template: src=database.yml
            dest={{madek_root_dir}}/config/database.yml
            owner=madek
            mode=0755

- name: Apache site config
  template: src=apache.conf
            dest=/etc/apache2/sites-available/madek.conf
            mode=0755

- name: Enable site 
  file: src=/etc/apache2/sites-available/madek.conf dest=/etc/apache2/sites-enabled/madek.conf state=link
  register: enable_site

- name: Bundle
  shell: su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
          && rbenv-load 
          && cd {{madek_root_dir}}
          && export RAILS_ENV={{rails_env}} 
          && export RBENV_VERSION={{mri_ruby_version}} 
          && bundle install --deployment' madek
         executable=/bin/bash
  register: bundle
  changed_when: bundle.stdout | match(".*Installing.*")

- name: Setup madek dirs
  shell:  su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
            && rbenv-load 
            && cd {{madek_root_dir}}
            && export RAILS_ENV={{rails_env}} 
            && export RBENV_VERSION={{mri_ruby_version}} 
            && bundle exec rake madek:setup:dirs' madek
          executable=/bin/bash
  changed_when: False

- name: Migrate
  shell:  su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
            && rbenv-load 
            && cd {{madek_root_dir}}
            && export RAILS_ENV={{rails_env}} 
            && export RBENV_VERSION={{mri_ruby_version}} 
            && bundle exec rake db:create db:migrate' madek
          executable=/bin/bash
  register: migrate
  changed_when: not migrate.stdout | match("")

- name: Precompile assets 
  shell:  su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
            && rbenv-load 
            && cd {{madek_root_dir}}
            && export RAILS_ENV={{rails_env}} 
            && export RBENV_VERSION={{mri_ruby_version}} 
            && rm -rf public/assets/*"
            && rm -rf tmp/cache/*"
            && bundle exec rake assets:precompile' madek
          executable=/bin/bash
  register: precompile_assets
  changed_when: not precompile_assets.stderr | match("")


- service:  name=apache2
            state=reloaded

- name: Passenger reload app
  file: path={{madek_root_dir}}/tmp/restart.txt
        state=touch



