- template: >
    src=dump.sh
    dest=/etc/cron.daily/madek-db-backup-{{rails_env}}
    mode=0755
  when: db_backups_enabled

- file: >
    path=/etc/cron.daily/madek-db-backup-{{rails_env}}
    state=absent 
  when: not db_backups_enabled

- template: >
    src=dump_data.sh
    dest=/etc/cron.daily/madek-db-data-dump-{{rails_env}}
    mode=0755
  when: db_dump_data_enabled

- file: >
    path=/etc/cron.daily/madek-db-data-dump-{{rails_env}}
    state=absent 
  when: not db_dump_data_enabled

