- apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: 
    - whois 
    - apg



### store api key ##############################################################

- shell : echo '{{zencoder_api_key}}' > {{zencoder_api_key_file}}
  when: zencoder_api_key is defined

- stat: path={{zencoder_api_key_file}} 
  register: zencoder_api_key_file_stat

- shell : cat {{zencoder_api_key_file}}
  register: zencoder_api_key_file_content
  changed_when: False
  when: zencoder_api_key_file_stat.stat.exists

- set_fact: zencoder_api_key="{{zencoder_api_key_file_content.stdout}}"
  when: zencoder_api_key_file_stat.stat.exists


### salt for zencoder_inbox pw #################################################

- shell:  apg -n 1 -x 10 -m 10 -M sNC > /etc/madek/zencoder_inbox_salt.txt
          creates=/etc/madek/zencoder_inbox_salt.txt

- file: path=/etc/madek/zencoder_inbox_salt.txt mode=0700

- shell : cat /etc/madek/zencoder_inbox_salt.txt
  register: zencoder_inbox_salt_task
  changed_when: False


### zencoder_inbox pw ##########################################################

- shell:  apg -n 1 -x 10 -m 10 -M sNC > /etc/madek/zencoder_inbox_pw.txt
          creates=/etc/madek/zencoder_inbox_pw.txt

- file: path=/etc/madek/zencoder_inbox_pw.txt mode=0700

- shell : cat /etc/madek/zencoder_inbox_pw.txt
  register: zencoder_inbox_pw_task
  changed_when: False

- set_fact: zencoder_inbox_pw="{{zencoder_inbox_pw_task.stdout}}"

- debug: var=zencoder_inbox_pw

### zencoder_inbox user ########################################################

- command: mkpasswd --method=SHA-512 -S '{{zencoder_inbox_salt_task.stdout}}' '{{zencoder_inbox_pw}}'
  register: zencoder_inbox_password_hash 
  changed_when: False

- user: name=zencoder-import
        remove=true
        state=absent 
  ignore_errors: yes

- user: name=zencoder
        shell=/usr/sbin/nologin
        group=madek
        uid=1006
        home={{zencoder_inbox_root_path}}
        password={{zencoder_inbox_password_hash.stdout}}

- file: path={{zencoder_inbox_root_path}}
        owner=root
        group=madek
        state=directory
        mode=0710

- file: path={{zencoder_inbox_root_path}}/import
        owner=zencoder
        group=madek
        state=directory
        mode=0770

- template: src=zencoder.local.yml 
            dest={{madek_root_dir}}/config/zencoder.local.yml
            mode=0600
            owner=madek
  register: zencoder_config

- file: src=zencoder.custom.yml 
        force=false
        dest={{madek_root_dir}}/config/zencoder.local.yml
        mode=0600
        owner=madek


- name: Passenger reload madek
  file: path={{madek_root_dir}}/tmp/restart.txt
        state=touch
  when: zencoder_config.changed


### sweep zencoder_inbox files after 3 days ####################################

- template: src=sweep-zencoder-inbox
            dest=/etc/cron.hourly/sweep-zencoder-inbox
            mode=0755

